name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装pnpm
        run: npm install --global pnpm
      - name: 安装依赖
        run: pnpm install
      - name: 推送Vercel环境信息
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 对项目进行打包
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: 部署项目
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}